### ISSUE TITLE
Already prefixed `text-decoration` results in duplicate `-webkit-text-decoration`

### ISSUE THREAD

**Issue by anttikivi** [parcel-bundler/lightningcss#872]
When transforming the following code:

```css
a {
  color: inherit;
  -webkit-text-decoration: inherit;
  text-decoration: inherit;
}
```

I get the following output:

```css
a {
  color: inherit;
  -webkit-text-decoration: inherit;
  -webkit-text-decoration: inherit;
  text-decoration: inherit;
}
```

This seems to be similar to at least #403. It happens in both Lightning CSS v1.28.2 and when using the local version.

[Playground](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22customMedia%22%3Afalse%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22safari%22%3A1179648%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22a%20%7B%5Cn%20%20color%3A%20inherit%3B%5Cn%20%20-webkit-text-decoration%3A%20inherit%3B%5Cn%20%20text-decoration%3A%20inherit%3B%5Cn%7D%5Cn%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)

**Comment by jonasgeiler** [comment]
Same problem here! Using TailwindCSS's preflight stylesheet and it includes some prefixes already, which then turns into duplicate prefixes... For me it's even 4 duplicates!
```
  a {
    color: inherit;
    -webkit-text-decoration: inherit;
    -webkit-text-decoration: inherit;
    -webkit-text-decoration: inherit;
    -webkit-text-decoration: inherit;
    text-decoration: inherit;
  }
```

**Comment by yisibl** [comment]
It appears this has been fixed in #403.

**Comment by callmesangio** [comment]
Bumping this up since it is still an issue as of version 1.31.1 (reporting this via Tailwind CSS 4.2.1).
